project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "clases/*.qmd"

website:
  title: "Taller Integrativo — Data Analytics para el Control de Gestión"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Clases"
        file: clases/index.qmd
      - text: "Recursos"
        href: recursos.qmd
      - text: "Contacto"
        href: contacto.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
